name: .helical_conda_venv
channels:
  - conda-forge
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - comm=0.2.3
  - debugpy=1.8.19
  - decorator=5.2.1
  - executing=2.2.1
  - icu=78.2
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=21.1.8
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - zeromq=4.3.5
  - pip:
      - accelerate==1.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anndata==0.12.7
      - antlr4-python3-runtime==4.9.3
      - array-api-compat==1.13.0
      - attrs==25.4.0
      - bitsandbytes==0.49.1
      - cattrs==25.3.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==3.6.0
      - deprecated==1.3.1
      - dill==0.3.8
      - donfig==0.8.1.post1
      - einops==0.8.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-crc32c==1.8.0
      - h5py==3.15.1
      - helical==1.5.3
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - igraph==0.11.9
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - legacy-api-wrap==1.5
      - leidenalg==0.10.2
      - llvmlite==0.46.0
      - loompy==3.0.7
      - louvain==0.8.2
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - natsort==8.4.0
      - networkx==3.6.1
      - numba==0.63.1
      - numcodecs==0.16.5
      - numpy==2.2.6
      - numpy-groupies==0.11.3
      - omegaconf==2.3.0
      - pandas==2.2.2
      - patsy==1.0.2
      - pillow==12.1.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - pyarrow==22.0.0
      - pybiomart==0.2.0
      - pydot==4.0.1
      - pynndescent==0.6.0
      - pyparsing==3.3.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-cache==1.2.1
      - safetensors==0.7.0
      - scanpy==1.11.5
      - scib==1.1.5
      - scikit-learn==1.8.0
      - scikit-misc==0.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - session-info2==0.3
      - smmap==5.0.2
      - statsmodels==0.14.6
      - sympy==1.14.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - torch==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - tzdata==2025.3
      - umap-learn==0.5.11
      - url-normalize==2.2.1
      - urllib3==2.6.3
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zarr==3.1.5
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/.helical_conda_venv
